import type * as THREE from 'three';
import type { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import type { TerrainState } from './terrain.ts';
import type { GravityState } from './gravity.ts';
export type Snapshot = {
  runId: string | null;
  mode: string;
  time: number;
  health: number;
  dodged: number;
  wave: number;
  distance: number;
  dash: number;
  message: string;
  ready: boolean;
};
type Hazard = {
  type: 'laser' | 'meteor';
  point: THREE.Vector3;
  normal: THREE.Vector3;
  age: number;
  delay: number;
  radius: number;
  group: THREE.Group;
  ring: THREE.Mesh<THREE.RingGeometry, THREE.MeshBasicMaterial>;
  disc: THREE.Mesh;
  body: THREE.Mesh;
  beam: THREE.Mesh;
  resolved: boolean;
  hit: boolean;
  h: number;
};
type Particle = {
  mesh: THREE.Mesh;
  v: THREE.Vector3;
  life: number;
  max: number;
};
export type GameOptions = { ratio: number; baseUrl: string };
export interface GameController {
  load(): Promise<void>;
  start(): void;
  overview(): void;
  togglePause(): void;
  setRatio(ratio: number): void;
  setMuted(muted: boolean): void;
  key(key: string, pressed: boolean): void;
  jump(): void;
  dash(): void;
  read(): Readonly<Snapshot>;
  dispose(): void;
}
export interface GameContext {
  assetUrls: Readonly<{ shoe: string; runner: string }>;
  host: HTMLElement;
  emit: (snapshot: Snapshot) => void;
  scene: THREE.Scene;
  camera: THREE.PerspectiveCamera;
  renderer: THREE.WebGLRenderer;
  controls: OrbitControls;
  stage: THREE.Group;
  player: THREE.Group;
  shadow: THREE.Mesh;
  reticle: THREE.Mesh;
  raf: number;
  last: number;
  disposed: boolean;
  shoe?: THREE.Group;
  ratio: number;
  terrain?: TerrainState;
  gravity: GravityState;
  avatar?: THREE.Group;
  mixer?: THREE.AnimationMixer;
  actions: Record<string, THREE.AnimationAction>;
  action: string;
  position: THREE.Vector3;
  spawnPoint: THREE.Vector3;
  velocity: THREE.Vector3;
  grounded: boolean;
  keys: Set<string>;
  hazards: Hazard[];
  particles: Particle[];
  nextHazard: number;
  dashTime: number;
  dashCooldown: number;
  invulnerable: number;
  targetFacing: number;
  currentFacing: number;
  orbitalYaw: number;
  orbitalPitch: number;
  cameraDistance: number;
  pointer?: { x: number; y: number };
  tick: number;
  transition: number;
  shake: number;
  muted: boolean;
  audio?: AudioContext;
  webAbort: AbortController;
  state: Snapshot;
  cleanupInput: () => void;
  onFrame: (time: number) => void;
  loadPromise?: Promise<void>;
}
